### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [krystalgamer/Resonance#1]
this looks so cool, but is there any README with more details?

keep it up, cheers!

**Comment by krystalgamer** [comment]
In the next update, i'll push a README too.
Can't believe i forgot it ;_;
EDIT: New updates pushed and README was added. Thanks for noticing it :D

**Comment by aquynh** [comment]
Great, but can you fix the link to Casptone in README? thanks.

**Comment by krystalgamer** [comment]
Fixed, sorry for the inconvenient.
